#!/usr/bin/env python3
"""
Polymarket Trade Monitor
Real-time monitor for large trades on Polymarket with anomaly detection.
"""

import time
import csv
import requests
import os
import sys
from datetime import datetime
from pathlib import Path

# Rich library for beautiful terminal output
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.prompt import Prompt, Confirm
from rich.text import Text
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich import box

# Load environment variables from .env file
from dotenv import load_dotenv

# --- INITIALIZATION ---
console = Console()
load_dotenv()

# --- CONFIG (loaded from .env or defaults) ---
DISCORD_WEBHOOK = os.getenv("DISCORD_WEBHOOK", "")
MIN_TRADE_AMOUNT = int(os.getenv("MIN_TRADE_AMOUNT", "1000"))
LOOP_INTERVAL = int(os.getenv("LOOP_INTERVAL", "1"))
ANOMALY_PRICE_MAX = float(os.getenv("ANOMALY_PRICE_MAX", "0.4"))
ANOMALY_SIZE_MIN = int(os.getenv("ANOMALY_SIZE_MIN", "10000"))
ANOMALY_AMOUNT_MIN = int(os.getenv("ANOMALY_AMOUNT_MIN", "500"))
MAX_TRADE_AGE_MINUTES = int(os.getenv("MAX_TRADE_AGE_MINUTES", "30"))

CSV_OUTPUT = "large_trades.csv"
TRACKED_WALLETS_FILE = "tracked_wallets.txt"
TRACKED_USERNAMES_FILE = "tracked_usernames.txt"

# --- RUNTIME STATE ---
notified_trades = {}
trade_cache_cleanup_counter = 0


def print_header():
    """Display a colorful header at startup."""
    header = Text()
    header.append("POLYMARKET", style="bold cyan")
    header.append(" TRADE ", style="bold white")
    header.append("MONITOR", style="bold magenta")

    console.print(Panel(
        header,
        subtitle="Real-time trade monitoring with anomaly detection",
        box=box.DOUBLE,
        border_style="cyan"
    ))
    console.print()


def needs_setup():
    """Check if initial setup is needed."""
    env_path = Path(".env")
    if not env_path.exists():
        return True
    # Check if webhook is not configured (optional but let's inform user)
    return False


def setup_wizard():
    """Interactive setup wizard for first-time configuration."""
    console.print(Panel(
        "[bold green]Welcome to Polymarket Monitor![/bold green]\n\n"
        "This wizard will help you configure the monitor.\n"
        "All settings will be saved to [cyan].env[/cyan] file.",
        title="Setup Wizard",
        box=box.ROUNDED,
        border_style="green"
    ))
    console.print()

    # Step 1: Discord Webhook
    console.print("[bold cyan]Step 1/4:[/bold cyan] Discord Notifications")
    console.print("Get a webhook URL from Discord: Server Settings > Integrations > Webhooks")
    console.print()

    webhook = Prompt.ask(
        "[yellow]Discord Webhook URL[/yellow] (press Enter to skip)",
        default=""
    )
    console.print()

    # Step 2: Minimum Trade Amount
    console.print("[bold cyan]Step 2/4:[/bold cyan] Minimum Trade Amount")
    console.print("Only trades above this USD amount will be monitored.")
    console.print()

    min_amount = Prompt.ask(
        "[yellow]Minimum trade amount ($)[/yellow]",
        default="1000"
    )
    try:
        min_amount = int(min_amount)
    except ValueError:
        min_amount = 1000
    console.print()

    # Step 3: Anomaly Criteria
    console.print("[bold cyan]Step 3/4:[/bold cyan] Anomaly Detection Criteria")
    console.print("Trades matching these criteria will be flagged as anomalous.")
    console.print()

    anomaly_price = Prompt.ask(
        "[yellow]Max price for anomaly (0.0-1.0)[/yellow]",
        default="0.4"
    )
    try:
        anomaly_price = float(anomaly_price)
    except ValueError:
        anomaly_price = 0.4

    anomaly_size = Prompt.ask(
        "[yellow]Min size for anomaly[/yellow]",
        default="10000"
    )
    try:
        anomaly_size = int(anomaly_size)
    except ValueError:
        anomaly_size = 10000
    console.print()

    # Step 4: Trade Age
    console.print("[bold cyan]Step 4/4:[/bold cyan] Maximum Trade Age")
    console.print("Trades older than this will be ignored.")
    console.print()

    max_age = Prompt.ask(
        "[yellow]Max trade age (minutes)[/yellow]",
        default="30"
    )
    try:
        max_age = int(max_age)
    except ValueError:
        max_age = 30
    console.print()

    # Save configuration
    env_content = f"""# Polymarket Monitor Configuration
# Generated by setup wizard

# Discord webhook URL for notifications (optional)
DISCORD_WEBHOOK={webhook}

# Minimum trade amount to monitor (USD)
MIN_TRADE_AMOUNT={min_amount}

# Anomaly detection criteria
ANOMALY_PRICE_MAX={anomaly_price}
ANOMALY_SIZE_MIN={anomaly_size}
ANOMALY_AMOUNT_MIN=500

# Maximum age of trades to consider (minutes)
MAX_TRADE_AGE_MINUTES={max_age}

# Check interval (seconds)
LOOP_INTERVAL=1
"""

    with open(".env", "w") as f:
        f.write(env_content)

    # Show summary
    summary_table = Table(title="Configuration Summary", box=box.ROUNDED, border_style="green")
    summary_table.add_column("Setting", style="cyan")
    summary_table.add_column("Value", style="white")

    summary_table.add_row("Discord Webhook", webhook[:30] + "..." if webhook else "[dim]Not configured[/dim]")
    summary_table.add_row("Min Trade Amount", f"${min_amount:,}")
    summary_table.add_row("Anomaly Price Max", str(anomaly_price))
    summary_table.add_row("Anomaly Size Min", f"{anomaly_size:,}")
    summary_table.add_row("Max Trade Age", f"{max_age} minutes")

    console.print(summary_table)
    console.print()
    console.print("[green]Configuration saved to .env[/green]")
    console.print()

    # Reload configuration
    load_dotenv(override=True)
    global DISCORD_WEBHOOK, MIN_TRADE_AMOUNT, ANOMALY_PRICE_MAX, ANOMALY_SIZE_MIN, MAX_TRADE_AGE_MINUTES
    DISCORD_WEBHOOK = os.getenv("DISCORD_WEBHOOK", "")
    MIN_TRADE_AMOUNT = int(os.getenv("MIN_TRADE_AMOUNT", "1000"))
    ANOMALY_PRICE_MAX = float(os.getenv("ANOMALY_PRICE_MAX", "0.4"))
    ANOMALY_SIZE_MIN = int(os.getenv("ANOMALY_SIZE_MIN", "10000"))
    MAX_TRADE_AGE_MINUTES = int(os.getenv("MAX_TRADE_AGE_MINUTES", "30"))


def send_discord_notification(trade):
    """Send a Discord notification for a trade."""
    try:
        if not DISCORD_WEBHOOK or DISCORD_WEBHOOK == "":
            return

        trader_stats = get_trader_stats(trade.get('trader_address', ''))
        is_anomalous = bool(trade.get('is_anomalous', False))

        if is_anomalous:
            description = (
                f"**ALERT: Low price + Large size!**\n\n"
                f"**Market:** {trade['market_title']}\n"
                f"**Amount:** ${trade['amount']:,.2f}\n"
                f"**Price:** {trade['price']:.4f} (<= {ANOMALY_PRICE_MAX})\n"
                f"**Size:** {trade['size']:,.2f} (>= {ANOMALY_SIZE_MIN:,})\n"
                f"**Outcome:** {trade['outcome']}\n"
                f"**Side:** {trade['side']}\n"
                f"**Trader:** {trade['trader']}\n"
                f"**Time:** {trade['timestamp']}\n\n"
            )
        else:
            description = (
                f"**Market:** {trade['market_title']}\n"
                f"**Amount:** ${trade['amount']:,.2f}\n"
                f"**Price:** {trade['price']:.4f}\n"
                f"**Size:** {trade['size']:,.2f}\n"
                f"**Outcome:** {trade['outcome']}\n"
                f"**Side:** {trade['side']}\n"
                f"**Trader:** {trade['trader']}\n"
                f"**Time:** {trade['timestamp']}\n\n"
            )

        if trader_stats:
            description += (
                f"**TRADER INFO:**\n"
                f"Markets Traded: {trader_stats['total_markets']}\n"
                f"Wallet: `{trader_stats['trader_address'][:10]}...{trader_stats['trader_address'][-6:]}`\n\n"
            )

        description += (
            f"[Trade ->]({trade['market_link']})\n"
            f"[Trader Profile ->]({trade['trader_link']})"
        )

        if is_anomalous:
            embed = {
                "title": f"ANOMALOUS TRADE: ${trade['amount']:,.2f}",
                "description": description,
                "color": 15158332  # red
            }
        else:
            embed = {
                "title": f"Trade update: ${trade['amount']:,.2f}",
                "description": description,
                "color": 3447003  # blue
            }

        payload = {"username": "Polymarket Monitor", "embeds": [embed]}
        requests.post(DISCORD_WEBHOOK, json=payload, timeout=10)
    except Exception as e:
        console.print(f"[red]Error sending Discord notification:[/red] {e}")


def save_to_csv(data):
    """Append results to CSV file."""
    if not data:
        return
    with open(CSV_OUTPUT, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=data[0].keys())
        if f.tell() == 0:
            writer.writeheader()
        writer.writerows(data)


def is_anomalous_trade(price, size, amount):
    """Check if a trade is anomalous based on low price and large size."""
    return (price <= ANOMALY_PRICE_MAX and
            size >= ANOMALY_SIZE_MIN and
            amount >= ANOMALY_AMOUNT_MIN)


def get_market_link(slug, condition_id):
    """Generate the correct market link on Polymarket."""
    if slug and slug != "unknown":
        return f"https://polymarket.com/market/{slug}"
    elif condition_id:
        return f"https://polymarket.com/market/{condition_id}"
    else:
        return "https://polymarket.com"


def get_trader_link(pseudonym, trader_address=None):
    """Generate the link to the trader profile on Polymarket."""
    if (trader_address and
        trader_address != "unknown" and
        trader_address != "" and
        trader_address.startswith("0x")):
        return f"https://polymarket.com/profile/{trader_address}"
    else:
        return f"Trader: {pseudonym} (address not available)"


def get_trader_stats(trader_address):
    """Fetch basic trader stats from Polymarket's API."""
    try:
        if not trader_address or trader_address == "unknown":
            return None

        url = f"https://data-api.polymarket.com/traded/{trader_address}"
        response = requests.get(url, timeout=5)

        if response.status_code == 200:
            data = response.json()
            total_markets = data.get('totalMarkets', 0)

            return {
                'total_markets': total_markets,
                'trader_address': trader_address
            }
    except Exception:
        pass
    return None


def fetch_trades(min_amount=None):
    """Fetch trades from Polymarket API."""
    try:
        params = {}
        if min_amount is not None:
            params = {
                'filterType': 'CASH',
                'filterAmount': min_amount
            }
        response = requests.get("https://data-api.polymarket.com/trades", params=params, timeout=10)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        console.print(f"[red]Error fetching trades:[/red] {e}")
        return []


def load_tracked_wallets():
    """Load tracked wallets from disk as a lowercase set."""
    if not os.path.exists(TRACKED_WALLETS_FILE):
        return set()
    wallets = set()
    try:
        with open(TRACKED_WALLETS_FILE, "r") as f:
            for line in f:
                w = line.strip()
                if w:
                    wallets.add(w.lower())
    except Exception as e:
        console.print(f"[yellow]Warning: Error loading tracked wallets file:[/yellow] {e}")
    return wallets


def load_tracked_usernames():
    """Load tracked Polymarket usernames as case-sensitive set."""
    if not os.path.exists(TRACKED_USERNAMES_FILE):
        return set()
    names = set()
    try:
        with open(TRACKED_USERNAMES_FILE, "r") as f:
            for line in f:
                n = line.strip()
                if n:
                    names.add(n)
    except Exception as e:
        console.print(f"[yellow]Warning: Error loading tracked usernames file:[/yellow] {e}")
    return names


def save_tracked_wallets(wallets):
    """Persist tracked wallets to disk."""
    try:
        with open(TRACKED_WALLETS_FILE, "w") as f:
            for w in sorted({w.lower() for w in wallets}):
                f.write(w + "\n")
        console.print(f"[green]Saved {len(wallets)} wallet(s) to {TRACKED_WALLETS_FILE}[/green]")
    except Exception as e:
        console.print(f"[red]Error saving tracked wallets:[/red] {e}")


def save_tracked_usernames(usernames):
    """Persist tracked usernames to disk."""
    try:
        with open(TRACKED_USERNAMES_FILE, "w") as f:
            for n in sorted(set(usernames)):
                f.write(n + "\n")
        console.print(f"[green]Saved {len(usernames)} username(s) to {TRACKED_USERNAMES_FILE}[/green]")
    except Exception as e:
        console.print(f"[red]Error saving tracked usernames:[/red] {e}")


def choose_mode():
    """Prompt the user to choose the operating mode with styled menu."""
    menu_table = Table(box=box.ROUNDED, border_style="cyan", show_header=False)
    menu_table.add_column("Option", style="bold yellow", width=4)
    menu_table.add_column("Description", style="white")

    menu_table.add_row("1", f"Monitor large trades (>= ${MIN_TRADE_AMOUNT:,})")
    menu_table.add_row("2", "Track specific wallets/usernames")
    menu_table.add_row("3", "Exit")

    console.print(Panel(menu_table, title="Select Mode", border_style="cyan"))
    console.print()

    while True:
        choice = Prompt.ask("[cyan]Enter choice[/cyan]", choices=["1", "2", "3"], default="1")
        return choice


def display_trade(trade_info, is_anomalous):
    """Display a trade with rich formatting."""
    if is_anomalous:
        style = "bold red"
        title = "ANOMALOUS TRADE DETECTED"
        border_style = "red"
    else:
        style = "cyan"
        title = "Trade"
        border_style = "blue"

    trade_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 1))
    trade_table.add_column("Field", style="dim")
    trade_table.add_column("Value", style=style)

    trade_table.add_row("Hash", trade_info['trade_hash'][:16] + "...")
    trade_table.add_row("Amount", f"${trade_info['amount']:,.2f}")
    trade_table.add_row("Price", f"{trade_info['price']:.4f}")
    trade_table.add_row("Size", f"{trade_info['size']:,.2f}")
    trade_table.add_row("Market", trade_info['market_title'][:50] + "..." if len(trade_info['market_title']) > 50 else trade_info['market_title'])
    trade_table.add_row("Outcome", trade_info['outcome'])
    trade_table.add_row("Side", trade_info['side'])
    trade_table.add_row("Trader", trade_info['trader'])
    trade_table.add_row("Time", trade_info['timestamp'])

    if is_anomalous:
        alert_text = Text()
        alert_text.append("Low price: ", style="yellow")
        alert_text.append(f"{trade_info['price']:.4f} <= {ANOMALY_PRICE_MAX}\n", style="white")
        alert_text.append("Large size: ", style="yellow")
        alert_text.append(f"{trade_info['size']:,.2f} >= {ANOMALY_SIZE_MIN:,}", style="white")
        console.print(Panel(
            alert_text,
            title=f"[bold red]{title}[/bold red]",
            border_style=border_style,
            box=box.HEAVY
        ))

    console.print(Panel(trade_table, border_style=border_style))


def main_loop(tracked_wallets=None, tracked_usernames=None):
    """Main monitoring loop."""
    global trade_cache_cleanup_counter

    # Display configuration
    config_table = Table(title="Active Configuration", box=box.ROUNDED, border_style="green")
    config_table.add_column("Setting", style="cyan")
    config_table.add_column("Value", style="white")

    if tracked_wallets or tracked_usernames:
        config_table.add_row("Mode", "[yellow]Tracking Mode[/yellow]")
        if tracked_wallets:
            config_table.add_row("Tracked Wallets", str(len(tracked_wallets)))
        if tracked_usernames:
            config_table.add_row("Tracked Usernames", str(len(tracked_usernames)))
    else:
        config_table.add_row("Mode", "[cyan]Large Trade Monitor[/cyan]")
        config_table.add_row("Min Trade Amount", f"${MIN_TRADE_AMOUNT:,}")

    config_table.add_row("Anomaly Criteria", f"price <= {ANOMALY_PRICE_MAX}, size >= {ANOMALY_SIZE_MIN:,}")
    config_table.add_row("Max Trade Age", f"{MAX_TRADE_AGE_MINUTES} minutes")
    config_table.add_row("Discord Webhook", "[green]Configured[/green]" if DISCORD_WEBHOOK else "[dim]Not configured[/dim]")

    console.print(config_table)
    console.print()
    console.print("[bold green]Starting monitor...[/bold green] Press Ctrl+C to stop.\n")

    while True:
        try:
            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=console,
                transient=True
            ) as progress:
                task = progress.add_task("Fetching trades...", total=None)

                if tracked_wallets or tracked_usernames:
                    trades = fetch_trades(min_amount=None)
                else:
                    trades = fetch_trades(min_amount=MIN_TRADE_AMOUNT)

            if trades:
                trade_count = len(trades)
                if tracked_wallets or tracked_usernames:
                    console.print(f"[dim]Received {trade_count} trades (no amount filter)[/dim]")
                else:
                    console.print(f"[dim]Received {trade_count} trades >= ${MIN_TRADE_AMOUNT:,}[/dim]")

                if tracked_wallets or tracked_usernames:
                    trades_to_show = trades
                else:
                    trades_to_show = trades[:10]

                new_trades_count = 0
                anomalous_trades_count = 0

                for trade in trades_to_show:
                    trade_id = trade.get("transactionHash", "unknown")
                    timestamp = trade.get("timestamp", 0)

                    trader_address = (trade.get("trader", "") or "").lower()
                    pseudonym = trade.get("pseudonym", "")

                    if tracked_wallets or tracked_usernames:
                        allowed = False
                        if tracked_wallets and trader_address in tracked_wallets:
                            allowed = True
                        if tracked_usernames and pseudonym in tracked_usernames:
                            allowed = True
                        if not allowed:
                            continue

                    trade_key = f"{trade_id}_{timestamp}"
                    if trade_key in notified_trades:
                        continue

                    if timestamp:
                        trade_time = datetime.utcfromtimestamp(timestamp)
                        time_diff = datetime.utcnow() - trade_time
                        age_minutes = time_diff.total_seconds() / 60
                        if age_minutes > MAX_TRADE_AGE_MINUTES:
                            continue

                    try:
                        trade_ts = int(timestamp) if timestamp else int(datetime.utcnow().timestamp())
                    except Exception:
                        trade_ts = int(datetime.utcnow().timestamp())
                    notified_trades[trade_key] = trade_ts

                    price = float(trade.get("price", 0))
                    size = float(trade.get("size", 0))
                    amount = price * size
                    title = trade.get("title", "Unknown Market")
                    slug = trade.get("slug", "unknown")
                    condition_id = trade.get("conditionId", "")
                    side = trade.get("side", "Unknown")
                    outcome = trade.get("outcome", "Unknown")
                    pseudonym = trade.get("pseudonym", "Anonymous")

                    if timestamp:
                        ts = datetime.utcfromtimestamp(timestamp).strftime("%Y-%m-%d %H:%M:%S")
                    else:
                        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

                    is_anomalous = is_anomalous_trade(price, size, amount)
                    market_link = get_market_link(slug, condition_id)
                    trader_link = get_trader_link(pseudonym, trader_address)

                    trade_info = {
                        "trade_hash": trade_id,
                        "amount": amount,
                        "price": price,
                        "size": size,
                        "market_title": title,
                        "market_slug": slug,
                        "market_link": market_link,
                        "outcome": outcome,
                        "side": side,
                        "trader": pseudonym,
                        "trader_address": trader_address,
                        "trader_link": trader_link,
                        "timestamp": ts,
                        "is_anomalous": is_anomalous
                    }

                    display_trade(trade_info, is_anomalous)
                    save_to_csv([trade_info])
                    new_trades_count += 1

                    is_tracking_mode = bool(tracked_wallets or tracked_usernames)
                    if is_tracking_mode or is_anomalous:
                        if is_anomalous:
                            anomalous_trades_count += 1
                        if DISCORD_WEBHOOK:
                            console.print("[dim]Sending Discord notification...[/dim]")
                            send_discord_notification(trade_info)

                if new_trades_count > 0:
                    summary = Text()
                    summary.append(f"Processed {new_trades_count} new trade(s)", style="green")
                    if anomalous_trades_count > 0:
                        summary.append(f" | {anomalous_trades_count} anomalous", style="bold red")
                    console.print(summary)
                else:
                    console.print("[dim]No new trades[/dim]")
            else:
                console.print("[dim]No trades available[/dim]")

        except KeyboardInterrupt:
            console.print("\n[yellow]Monitor stopped by user.[/yellow]")
            break
        except Exception as e:
            console.print(f"[red]Error during processing:[/red] {e}")

        # Periodic cache cleanup
        trade_cache_cleanup_counter += 1
        if trade_cache_cleanup_counter >= 100:
            now_ts = int(datetime.utcnow().timestamp())
            retention_secs = int(MAX_TRADE_AGE_MINUTES * 60)
            notified_trades_keys = list(notified_trades.keys())
            for k in notified_trades_keys:
                seen_ts = notified_trades.get(k, 0)
                if seen_ts <= 0 or (now_ts - seen_ts) > retention_secs:
                    notified_trades.pop(k, None)
            trade_cache_cleanup_counter = 0

        console.print(f"[dim]Next check in {LOOP_INTERVAL}s...[/dim]\n")
        time.sleep(LOOP_INTERVAL)


def main():
    """Main entry point."""
    print_header()

    # Check if setup is needed
    if needs_setup():
        console.print("[yellow]No configuration found. Starting setup wizard...[/yellow]\n")
        setup_wizard()
    else:
        # Offer to run setup again
        console.print("[dim]Configuration loaded from .env[/dim]")
        console.print("[dim]Run with --setup to reconfigure[/dim]\n")

    # Check for --setup flag
    if "--setup" in sys.argv:
        setup_wizard()

    choice = choose_mode()

    if choice == "1":
        main_loop()
    elif choice == "2":
        existing_wallets = load_tracked_wallets()
        existing_usernames = load_tracked_usernames()

        if existing_wallets:
            console.print(f"[cyan]Found {len(existing_wallets)} existing wallet(s)[/cyan]")
        if existing_usernames:
            console.print(f"[cyan]Found {len(existing_usernames)} existing username(s)[/cyan]")
        console.print()

        raw_w = Prompt.ask(
            "[yellow]Enter wallet addresses to track[/yellow] (comma-separated, Enter to keep existing)",
            default=""
        )
        new_wallets = {w.strip().lower() for w in raw_w.split(',') if w.strip()}
        new_wallets = {w for w in new_wallets if w.startswith('0x') and len(w) == 42}

        raw_u = Prompt.ask(
            "[yellow]Enter Polymarket usernames to track[/yellow] (comma-separated, Enter to keep existing)",
            default=""
        )
        new_usernames = {u.strip() for u in raw_u.split(',') if u.strip()}

        tracked_wallets = set(existing_wallets)
        tracked_wallets.update(new_wallets)
        tracked_usernames = set(existing_usernames)
        tracked_usernames.update(new_usernames)

        if new_wallets:
            save_tracked_wallets(tracked_wallets)
        if new_usernames:
            save_tracked_usernames(tracked_usernames)

        if not tracked_wallets and not tracked_usernames:
            console.print("[yellow]No wallets or usernames to track. Exiting.[/yellow]")
        else:
            console.print()
            main_loop(tracked_wallets=tracked_wallets, tracked_usernames=tracked_usernames)
    else:
        console.print("[cyan]Goodbye![/cyan]")


if __name__ == "__main__":
    main()
